"""Company details table

Revision ID: 7c6adf8753f2
Revises: d607919c8314
Create Date: 2019-06-28 16:30:41.588959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c6adf8753f2'
down_revision = 'd607919c8314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_data', sa.Column('News_Date_to', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_data', 'News_Date_to')
    # ### end Alembic commands ###
