"""data table

Revision ID: c9bdd8d392e5
Revises: 7f914eb5cfd9
Create Date: 2019-06-21 19:33:44.924495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9bdd8d392e5'
down_revision = '7f914eb5cfd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('Contact_Record_Type', sa.String(length=64), nullable=True),
    sa.Column('Created_Date', sa.String(length=64), nullable=True),
    sa.Column('Contact_ID', sa.String(length=64), nullable=False),
    sa.Column('Contact_Owner', sa.String(length=64), nullable=True),
    sa.Column('First_Name', sa.String(length=64), nullable=True),
    sa.Column('Last_Name', sa.String(length=64), nullable=True),
    sa.Column('Title', sa.String(length=64), nullable=True),
    sa.Column('Account_Name', sa.String(length=64), nullable=True),
    sa.Column('Industry', sa.String(length=64), nullable=True),
    sa.Column('Email1', sa.String(length=64), nullable=True),
    sa.Column('Email2', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('Contact_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    # ### end Alembic commands ###
