"""Company details table

Revision ID: d607919c8314
Revises: 4336a3e22477
Create Date: 2019-06-28 16:24:42.603461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd607919c8314'
down_revision = '4336a3e22477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_data',
    sa.Column('Company', sa.String(length=64), nullable=False),
    sa.Column('Industry', sa.String(length=64), nullable=True),
    sa.Column('News_Date_from', sa.DateTime(), nullable=True),
    sa.Column('Mapped_to', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('Company')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_data')
    # ### end Alembic commands ###
